name: CD

on:
  push:
    branches: [master]

jobs:
  deploy-front:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: cd front && yarn install

      - name: Build Vue app
        env:
          VUE_APP_API_BASE_URL: ${{ secrets.VUE_APP_API_BASE_URL }}
        run: cd front && yarn build

      - name: Copy Vue build to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: front/dist
          remote: /home/erwan/YATDA/front/dist
          host: ${{ secrets.HOST }}
          username: erwan
          privateKey: ${{ secrets.SSH_KEY }}

  deploy-back:
    runs-on: ubuntu-latest

    steps:
      - name: Update repo and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: erwan
          key: ${{ secrets.SSH_KEY }}
          script: |
            source .profile
            cd YATDA/back
            git pull
            poetry install
            sudo service yatda restart
